In [1]:
import pandas as pd
import numpy as np
from geopy.geocoders import Nominatim
from geopy.exc import GeocoderTimedOut
import time
import cv2 

In [87]:
df = pd.read_csv('supermarkets.csv')

In [88]:
type(df)

pandas.core.frame.DataFrame

In [89]:
df

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [90]:
cols = df.columns[1:5]

In [91]:
completeAddr = ''
for i in cols:
    completeAddr += ' ' + df[i]

In [92]:
df

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [94]:
df.drop(labels=cols, axis=1, inplace=True)

In [95]:
df

ID         Name  Employees
0   1      Madeira          8
1   2  Bready Shop         15
2   3  Super River         25
3   4   Ben's Shop         10
4   5      Sanchez         12
5   6   Richvalley         20

In [96]:
df['Address'] = completeAddr

In [97]:
df

ID         Name  Employees                                          Address
0   1      Madeira          8          3666 21st St San Francisco CA 94114 USA
1   2  Bready Shop         15        735 Dolores St San Francisco CA 94119 USA
2   3  Super River         25   332 Hill St San Francisco California 94114 USA
3   4   Ben's Shop         10          3995 23rd St San Francisco CA 94114 USA
4   5      Sanchez         12     1056 Sanchez St San Francisco California USA
5   6   Richvalley         20       551 Alvarado St San Francisco CA 94114 USA

In [47]:
nom = Nominatim(user_agent='lucifer')

In [62]:
loc = nom.geocode('3666 21st St San Francisco CA 94114 USA')

In [65]:
type(loc)

geopy.location.Location

In [67]:
loc

Location(3666, 21st Street, Noe Valley, SF, California, 94114, USA, (37.756488877551, -122.429343346939, 0.0))

In [74]:
loc.longitude

-122.429343346939

In [75]:
loc.latitude

37.756488877551

In [76]:
loc.address

'3666, 21st Street, Noe Valley, SF, California, 94114, USA'

In [77]:
loc[0]

'3666, 21st Street, Noe Valley, SF, California, 94114, USA'

In [78]:
loc.altitude

0.0

In [79]:
loc.point

Point(37.756488877551, -122.429343346939, 0.0)

In [80]:
loc[1]

(37.756488877551, -122.429343346939)

In [82]:
loc.raw

{'place_id': 205948913,
 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright',
 'osm_type': 'way',
 'osm_id': 133452336,
 'boundingbox': ['37.756438877551',
  '37.756538877551',
  '-122.42939334694',
  '-122.42929334694'],
 'lat': '37.756488877551',
 'lon': '-122.429343346939',
 'display_name': '3666, 21st Street, Noe Valley, SF, California, 94114, USA',
 'class': 'place',
 'type': 'house',
 'importance': 0.6309999999999999}

In [99]:
loc.raw['importance']

0.6309999999999999

In [101]:
df['Address'][0]

' 3666 21st St San Francisco CA 94114 USA'

In [105]:
time.sleep(1)

In [110]:
locations = []
i = 0
while i < len(df['Address']):
    try:
        locations.append(nom.geocode(df['Address'][i]))
        i += 1
        time.sleep(2)
    except GeocoderTimedOut:
        continue

In [135]:
lats = list(map(lambda loc: loc.latitude, locations))

In [137]:
longs = list(map(lambda loc: loc.longitude, locations))

In [138]:
df['Latitude'] = lats
df['Longitude'] = longs

In [142]:
df

ID         Name  Employees  \
0   1      Madeira          8   
1   2  Bready Shop         15   
2   3  Super River         25   
3   4   Ben's Shop         10   
4   5      Sanchez         12   
5   6   Richvalley         20   

                                           Address   Latitude   Longitude  
0          3666 21st St San Francisco CA 94114 USA  37.756489 -122.429343  
1        735 Dolores St San Francisco CA 94119 USA  37.757726 -122.425529  
2   332 Hill St San Francisco California 94114 USA  37.755725 -122.428601  
3          3995 23rd St San Francisco CA 94114 USA  37.752965 -122.431714  
4     1056 Sanchez St San Francisco California USA  37.752146 -122.429815  
5       551 Alvarado St San Francisco CA 94114 USA  37.753673 -122.433220

In [143]:
imps = list(map(lambda loc: loc.raw['importance'], locations))

In [144]:
df['Importance'] = imps

In [145]:
df

ID         Name  Employees  \
0   1      Madeira          8   
1   2  Bready Shop         15   
2   3  Super River         25   
3   4   Ben's Shop         10   
4   5      Sanchez         12   
5   6   Richvalley         20   

                                           Address   Latitude   Longitude  \
0          3666 21st St San Francisco CA 94114 USA  37.756489 -122.429343   
1        735 Dolores St San Francisco CA 94119 USA  37.757726 -122.425529   
2   332 Hill St San Francisco California 94114 USA  37.755725 -122.428601   
3          3995 23rd St San Francisco CA 94114 USA  37.752965 -122.431714   
4     1056 Sanchez St San Francisco California USA  37.752146 -122.429815   
5       551 Alvarado St San Francisco CA 94114 USA  37.753673 -122.433220   

   Importance  
0       0.631  
1       0.521  
2       0.641  
3       0.631  
4       0.631  
5       0.631

In [146]:
df.to_csv('supermarket_lat_long.csv')

In [3]:
# cv2 readrs BGR instead of RGB
cv2.imread('smallgray.png')

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [6]:
bgr = cv2.imread('smallgray.png', 1)

In [7]:
bgr

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [8]:
grey = cv2.imread('smallgray.png', 0)

In [9]:
grey

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [10]:
grey.T

array([[187, 198, 209],
       [158, 125, 134],
       [104, 255, 255],
       [121, 255,  97],
       [143, 147, 182]], dtype=uint8)

In [13]:
list(grey.flat)

[187, 158, 104, 121, 143, 198, 125, 255, 255, 147, 209, 134, 255, 97, 182]

In [16]:
grey.flatten()

array([187, 158, 104, 121, 143, 198, 125, 255, 255, 147, 209, 134, 255,
        97, 182], dtype=uint8)

In [18]:
grey.view()

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [22]:
g1 = np.hstack((grey, grey))

In [23]:
g2 = np.vstack((g1, g1))

In [24]:
g2

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [28]:
cv2.imshow('image', grey)

In [ ]:
cv2.imwrite(midgrey, g2)